[package]
name = "snapshot_repeat"
version = "0.1.0"
authors = ["ametisf <ametisf@ametisf@gmail.com>"]
edition = "2018"

[dependencies]
# vst = { path = "../vst-rs" }
vst = { git = "https://github.com/RustAudio/vst-rs", rev = "02847c7" }

[lib]
name = "snapshot_repeat"
crate-type = ["cdylib"]
